#!/usr/bin/env python
import os
import shutil

from rootpy.io import root_open
from rootpy.tree import TreeModel, FloatCol
from rootpy.stl import vector

import logging
from multiprocessing import Process
import ROOT

from tauperf.extern import (
    ReadBDT_1p_odd, ReadBDT_1p_even,
    ReadBDT_mp_odd, ReadBDT_mp_even)
    
from tauperf.categories import Category_1P_HLT, Category_MP_HLT
from tauperf.variables import VARIABLES

log = logging.getLogger('apply-bdt-weights')


features_1p = vector('string')()
for var in Category_1P_HLT.features:
    features_1p.push_back('hlt_'+VARIABLES[var]['name'])
features_mp = vector('string')()
for var in Category_MP_HLT.features:
    features_mp.push_back('hlt_'+VARIABLES[var]['name'])

features = {
    '1p': features_1p,
    'mp': features_mp,
}

features_1p_pileup_corrected = vector('string')()
for var in Category_1P_HLT.features_pileup_corrected:
    features_1p_pileup_corrected.push_back('hlt_'+VARIABLES[var]['name'])
features_mp_pileup_corrected = vector('string')()
for var in Category_MP_HLT.features_pileup_corrected:
    features_mp_pileup_corrected.push_back('hlt_'+VARIABLES[var]['name'])
    
features_pileup_corrected = {
    '1p': features_1p_pileup_corrected,
    'mp': features_mp_pileup_corrected,
}

readers = {
    '1p_even': ReadBDT_1p_even(features_1p),
    '1p_odd': ReadBDT_1p_odd(features_1p),
    'mp_even': ReadBDT_mp_even(features_mp),
    'mp_odd': ReadBDT_mp_odd(features_mp),
}

readers_pileup_corrected = {
    '1p_even': ReadBDT_1p_even(features_1p_pileup_corrected),
    '1p_odd': ReadBDT_1p_odd(features_1p_pileup_corrected),
    'mp_even': ReadBDT_mp_even(features_mp_pileup_corrected),
    'mp_odd': ReadBDT_mp_odd(features_mp_pileup_corrected),
}


def evaluate_single_bdt(reader, feats, tree):
    vals = vector('double')()
    for feat in feats:
        vals.push_back(getattr(tree, feat))
    return reader.GetMvaValue(vals)

def evaluate_bdt(tree, readers, feats):
    if tree.hlt_tau.ntracks == 1:
        if tree.eventnumber % 2 == 0:
            return evaluate_single_bdt(
                readers['1p_even'], feats['1p'], tree)
        else:
            return evaluate_single_bdt(
                readers['1p_odd'], feats['1p'], tree)
    elif tree.hlt_tau.ntracks > 1:
        if tree.eventnumber % 2 == 0:
            return evaluate_single_bdt(
                readers['mp_even'], feats['mp'], tree)
        else:
            return evaluate_single_bdt(
                readers['mp_odd'], feats['mp'], tree)
    else:
        return -9999.

class Model(TreeModel):
    hlt_bdt_score = FloatCol()
    hlt_bdt_score_pileup_corrected = FloatCol()

def add_bdt_scores(tree):
    tree.create_buffer()
    tree.set_buffer(Model(), create_branches=True)
    branches = [
        tree.GetBranch('hlt_bdt_score'),
        tree.GetBranch('hlt_bdt_score_pileup_corrected'),
        ]
    tree.define_object('hlt_tau', prefix='hlt_')

    for event in tree:
        tree.hlt_bdt_score = evaluate_bdt(tree, readers, features)
        tree.hlt_bdt_score_pileup_corrected = evaluate_bdt(
            tree, readers_pileup_corrected, features_pileup_corrected)
        for branch in branches:
            branch.Fill()
    tree.SetEntries(-1)

class Job(Process):
    def __init__(self, filename):
        super(Job, self).__init__()
        self.filename = filename

    def run(self):
        filename = self.filename
        path, name = os.path.split(filename)
        # copy to new file
        output = os.path.join(path, 'weighted.' + name)
        if os.path.exists(output):
            return 
        log.info("copying {0} to {1} ...".format(filename, output))
        shutil.copy(filename, output)
        with root_open(output, 'UPDATE') as file:
            tree = file.tau
            if 'hlt_bdt_score' in tree:
                log.info("scores already exist in {0} ...".format(output))
                return
            log.info("adding bdt scores to {0} ...".format(output))
            add_bdt_scores(tree)
            tree.Write(tree.name, ROOT.TObject.kOverwrite)


if __name__ == '__main__':
    from rootpy.extern.argparse import ArgumentParser

    parser = ArgumentParser()
    parser.add_argument('files', nargs='+')
    args = parser.parse_args()

    from tauperf.parallel import run_pool
    jobs = [Job(f) for f in args.files]
    run_pool(jobs, n_jobs=-1)


