#!/usr/bin/env python
import os
import logging
import rootpy
from rootpy.plotting.style import set_style
from tauperf.analysis import Analysis
from tauperf.categories import Category_1P_HLT
from tauperf.variables import VARIABLES
from tauperf.plotting import draw_ratio

log = logging.getLogger(os.path.basename(__file__))
if not os.environ.get("DEBUG", False):
    log.setLevel(logging.INFO)
rootpy.log.setLevel(logging.INFO)
set_style('ATLAS', shape='rect')


if __name__ == "__main__":
    from argparse import ArgumentParser
    parser = ArgumentParser()
    parser.add_argument('--logy', default=False, action='store_true')
    args = parser.parse_args()

    ipsig_BS = {'ipSigLeadTrk_BS': VARIABLES['ipSigLeadTrk_BS']} 
    ipsig_PV = {'ipSigLeadTrk': VARIABLES['ipSigLeadTrk']} 
    
    ana = Analysis()
    hist_samples_hlt_BS = ana.get_hist_samples_array(ipsig_BS, 'hlt', Category_1P_HLT)
    hist_samples_hlt_PV = ana.get_hist_samples_array(ipsig_PV, 'hlt', Category_1P_HLT)

    hist_samples_hlt_BS['ipSigLeadTrk_BS']['tau'].title += ' (BS)'
    hist_samples_hlt_PV['ipSigLeadTrk']['tau'].title += ' (PV)'

    plot_bs_pv = draw_ratio(
        hist_samples_hlt_BS['ipSigLeadTrk_BS']['tau'], 
        hist_samples_hlt_PV['ipSigLeadTrk']['tau'],
        'S_{lead track}', Category_1P_HLT, logy=args.logy)
    plot_bs_pv.SaveAs(os.path.join('plots', 'bs_vs_pv_ipSigLeadTrk_'+Category_1P_HLT.name+'.png'))


