#!/usr/bin/env python
import os
import sys
import shutil
import logging
import rootpy
from rootpy.io import root_open
from rootpy.tree import Cut

log = logging.getLogger(os.path.basename(__file__))
if not os.environ.get("DEBUG", False):
    log.setLevel(logging.INFO)
rootpy.log.setLevel(logging.INFO)


if __name__ == "__main__":
    from argparse import ArgumentParser
    parser = ArgumentParser()
    parser.add_argument('file', type=str)
    args = parser.parse_args()

    filename = args.file
    path, name = os.path.split(args.file)

    output = os.path.join(path, 'training.' + name)
    if os.path.exists(output):
        sys.exit()
    log.info("copying {0} to {1} ...".format(filename, output))
    shutil.copy(filename, output)
    with root_open(output, 'UPDATE') as rfile:
        tree = rfile.tau
        tree_even = tree.CopyTree('eventnumber % 2 == 0')
        tree_odd =  tree.CopyTree('eventnumber % 2 != 0')
        tree_even.name = 'tau_even'
        tree_odd.name = 'tau_odd'
        
        tree_even.Write(tree_even.name)
        tree_odd.Write(tree_odd.name)
        
