#!/usr/bin/env python

# python imports
import os

# root/rootpy imports
from rootpy.extern.tabulartext import PrettyTable

# local imports
from tauid import log; log=log['print-variables']
from tauid.tauid import get_IDtools


tools = get_IDtools()
tables = []
for name, id in get_IDtools().items():
    for key, tool in id.tools.items():
        table = PrettyTable(['Menu:{0}, {1} taus'.format(name, key)])
        for var in tool.vars:
            table.add_row([var['name']])
        tables.append(table)

for table in tables:
    print table
