#!/usr/bin/env python

import sys
import os
import cluster

setup = cluster.get_setup(os.path.join(
    os.path.dirname(cluster.__file__), 'setup.sfu.txt'))
cmd = ' '.join(sys.argv[1:])
name = cmd.replace(" ", "_")
cmd = "cd %s && %s && %s" % (os.getcwd(), setup, cmd)

log_path = os.path.join(os.getcwd(), 'log')
stderr_path = log_path or os.getenv('PBS_STDERR', None)
stdout_path = log_path or os.getenv('PBS_STDOUT', None)

cluster.qsub(
    cmd,
    name=name,
    queue=os.getenv('PBS_QUEUE', 'medium'),
    ncpus=int(os.getenv('PBS_PPN', 1)),
    stdout_path=stdout_path,
    stderr_path=stderr_path)
