#!/usr/bin/env python
import os
import numpy as np
import tables

from tauperf import log; log = log['/tau-image']


def split_train(filename, n_chunks=3):
    """
    """
    log.info('open h5 file {0}'.format(filename))

    h5file = tables.open_file(filename, 'r+')
    print h5file
    group = h5file.root.data
    print group
    train = group.train
    trains = np.array_split(train.read(), n_chunks)
    for it, tr in enumerate(trains):
        print it
        h5file.create_table(group, 'train_{0}'.format(it), tr)

    log.info('close h5 file {0}'.format(filename))
    h5file.flush()
    h5file.close()
    log.info('')
    


if __name__ == '__main__':
    from argparse import ArgumentParser
    parser = ArgumentParser()
    parser.add_argument('h5file', help='path to the h5 input file')
    parser.add_argument('--chunks', default=3, type=int, help='number of training data chunks')
    args = parser.parse_args()

    h5_filename = args.h5file

    split_train(args.h5file, args.chunks)
