#!/usr/bin/env python
import os
import shutil

from rootpy.io import root_open
from rootpy.tree import TreeModel, FloatCol

import logging
from multiprocessing import Process
import ROOT
import array
    
from tauperf.categories import (Category_1P_HLT, Category_3P_HLT,
                                Category_1P, Category_3P)

log = logging.getLogger('test-xml-one-event')


# xml = 'weights_prod/1prong_hlt_even_features_pileup_corrected_BDT_1prong_hlt_even_features_pileup_corrected.weights.xml'
xml = 'weights_prod/3prongs_hlt_even_features_pileup_corrected_BDT_3prongs_hlt_even_features_pileup_corrected.weights.xml'
variables_values =  {
"centFracCorrected":  0.65432715416 ,
"etOverPtLeadTrkCorrected":  1.71604478359 ,
"innerTrkAvgDistCorrected":  0.0133473239839 ,
"ipSigLeadTrkCorrected":  0.0 ,
"SumPtTrkFrac":  0.05378607288 ,
"ptRatioEflowApproxCorrected":  0.916269242764 ,
"mEflowApproxCorrected":  1583.77453613 ,
"ChPiEMEOverCaloEMECorrected":  0.427297651768 ,
"EMPOverTrkSysPCorrected":  1.22171902657 ,
"dRmaxCorrected":  0.0418438911438 ,
"trFlightPathSigCorrected":  0.837903738022 ,
"massTrkSysCorrected":  2362.55297852 ,
}



variables = [
    'centFracCorrected',
    'etOverPtLeadTrkCorrected',
    'innerTrkAvgDistCorrected',
    'dRmaxCorrected',
    'trFlightPathSigCorrected',
    'massTrkSysCorrected',
    
    # 'ipSigLeadTrkCorrected',
    # 'SumPtTrkFrac',
    'ptRatioEflowApproxCorrected',
    'mEflowApproxCorrected',
    'ChPiEMEOverCaloEMECorrected',
    'EMPOverTrkSysPCorrected',
]


if __name__ == '__main__':



    reader = ROOT.TMVA.Reader()

    dummy_v = array.array('f', [0.])
    for f in variables:
        reader.AddVariable('hlt_' + f, dummy_v)

    reader.BookMVA('BDT', xml)
    feats = ROOT.vector('double')()
    for f in variables:
        feats.push_back(variables_values[f])
    print 'BDT score = ', reader.EvaluateMVA(feats, 'BDT')
