#!/usr/bin/env python
import os
import logging
import rootpy
from tauperf.analysis import Analysis
from tauperf.cmd import get_parser

log = logging.getLogger(os.path.basename(__file__))
if not os.environ.get("DEBUG", False):
    log.setLevel(logging.INFO)

rootpy.log.setLevel(logging.INFO)


if __name__ == "__main__":

    parser = get_parser('plot')
    parser.add_argument('--jobs', default=-1, type=int)
    args = parser.parse_args()
    
    ana = Analysis(
        use_drellyan=args.use_dy,
        trigger=args.trigger,
        no_weight=args.no_weight)


    ana.train(
        args.level, 
        ntrees=70,
        node_size=0.1,
        depth=10000,
        n_jobs=args.jobs)


