#!/usr/bin/env python
import os
import logging
import rootpy
from rootpy.plotting.style import set_style
from rootpy.plotting import Hist, Efficiency
from tauperf.plotting import draw_efficiencies
from tauperf.analysis import Analysis, old_working_points
from tauperf.variables import VARIABLES
from tauperf.cmd import get_parser
from prettytable import PrettyTable

log = logging.getLogger(os.path.basename(__file__))
if not os.environ.get("DEBUG", False):
    log.setLevel(logging.INFO)

rootpy.log.setLevel(logging.INFO)

set_style('ATLAS', shape='rect')
if __name__ == "__main__":

    parser = get_parser('plot')
    parser.add_argument('--jobs', default=-1, type=int)
    group_driver = parser.add_mutually_exclusive_group()
    group_driver.add_argument(
        '--target-eff', dest='target', 
        action='store_const', const='eff')
    group_driver.add_argument(
        '--target-rej', dest='target', 
        action='store_const', const='rej')
    group_driver.set_defaults(target='eff')
    parser.add_argument('--target-value', default=0.5, type=float)
    parser.add_argument('--score-var', default='hlt_bdt_score_hlt_training_nopucorr_dev', type=str)
    args = parser.parse_args()
    

    if args.trigger:
        wp_level = 'hlt'
    else:
        wp_level = 'off'

    ana = Analysis(
        use_drellyan=args.use_dy,
        trigger=args.trigger,
        no_weight=args.no_weight)

    # score_var = 'hlt_bdt_score_{1}_training_dev'.format(wp_level)
    
    score_var = args.score_var

    table = PrettyTable([
            "Category",
            "target",
            "efficiency",
            "cut value"])



    vars = {
        'pt': VARIABLES['pt'],
        'eta': VARIABLES['eta'],
        'good_npv': VARIABLES['good_npv'],
        'averageintpercrossing': VARIABLES['averageintpercrossing'],
        }


    for cat in ana.iter_categories(args.categories):
        _, wps = old_working_points(ana, cat, wp_level)

        for wp in wps:
            print wp.name, wp.eff_b
            
        target = wps[1].eff_b
        h_template = Hist(10000, 0, 1)
        hist = ana.jet.get_hist_array(
            {score_var: h_template},
            category=cat)
        hist = hist[score_var]
        
        bin = -1
        
        for ibin in xrange(hist.GetNbinsX()):
            eff = (hist.Integral() - hist.Integral(0, ibin)) / hist.Integral()
            if eff < target:
                bin = ibin
                cut_val = hist.GetBinLowEdge(bin)
                break
            # print hist.Integral(), hist.Integral(0, ibin), hist.GetBinContent(ibin)

        if bin == -1:
            continue

        table.add_row([
                cat.name, wps[1].eff_b, 
                (hist.Integral() - hist.Integral(0, ibin)) / hist.Integral(),
                hist.GetBinLowEdge(bin)])

        print table
        print cut_val
        hist_denom = ana.get_hist_samples_array(
            vars, wp_level, category=cat)
        hist_wp = ana.get_hist_samples_array(
            vars, wp_level, category=cat, cuts=wps[1].cut)
        hist_new = ana.get_hist_samples_array(
            vars, wp_level, category=cat, cuts='{0} > {1}'.format(
                score_var, cut_val))

        # sig_effs = {}
        # bkg_effs = {}
        # for v in vars.keys():
        #     sig_effs[v] = []
        #     bkg_effs[v] = []

        for v in vars.keys():
            sig_effs = [
                Efficiency(
                    hist_wp[v]['tau'],
                    hist_denom[v]['tau'],
                    title='MC15'),
                Efficiency(
                    hist_new[v]['tau'],
                    hist_denom[v]['tau'],
                    title='new tauID')]

            c_sig = draw_efficiencies(sig_effs, wp_level + '_' + v, cat)
            c_sig.SaveAs('./plots/new_wp_sig_comparison_{0}_{1}.png'.format(
                    v, cat.name))

            bkg_effs = [
                Efficiency(
                    hist_wp[v]['jet'],
                    hist_denom[v]['jet'],
                    title='MC15'),
                Efficiency(
                    hist_new[v]['jet'],
                    hist_denom[v]['jet'],
                    title='new tauID')]
            
            c_bkg = draw_efficiencies(bkg_effs, wp_level + '_' + v, cat)
            c_bkg.SaveAs('./plots/new_wp_bkg_comparison_{0}_{1}.png'.format(
                    v, cat.name))


    print table
