#!/usr/bin/env python
import os
# ROOT/rootpy imports
from rootpy.extern import argparse
from batch import qsub, get_setup
from tools.datasets import DATASETS, VERSION

parser = argparse.ArgumentParser()
parser.add_argument('--submit', action='store_true', default=False)
args = parser.parse_args()

setup = get_setup('batch/setup.sfu.txt')
for key, dataset in DATASETS.items():
    cmd_args = ['./eff-calculator', dataset['path'],
                'efficiencies/efficiencies_%s_v%d.root'%(key, VERSION)]
    if dataset['signal']:
        cmd_args.append('--signal')
    cmd = ' '.join(cmd_args)
    name = key 
    cmd = "cd %s && %s && %s" % (os.getcwd(), setup, cmd)
    if args.submit:
        qsub(cmd, name=name, ncpus=1)

